// <auto-generated />
namespace Seguridad.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class Usuario_Area : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(Usuario_Area));
        
        string IMigrationMetadata.Id
        {
            get { return "201603052239272_Usuario_Area"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
