// <auto-generated />
namespace VirtualOffice.Repositorios.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.1-30610")]
    public sealed partial class cambioDireccion : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(cambioDireccion));
        
        string IMigrationMetadata.Id
        {
            get { return "201509261223405_cambioDireccion"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
